# Generated by Django 4.2.4 on 2023-09-08 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugTracker', '0003_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_at',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teams',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='projects',
            field=models.ManyToManyField(null=True, related_name='teams', to='bugTracker.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teams',
            name='members',
            field=models.ManyToManyField(null=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
