# Generated by Django 4.2.4 on 2023-09-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugTracker', '0011_comments_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='bug_fix',
            field=models.TextField(null=True),
        ),
    ]
