# Generated by Django 4.2.4 on 2023-09-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugTracker', '0012_bugs_bug_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
