# Generated by Django 4.2.4 on 2023-09-10 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugTracker', '0007_bugs_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='bugTracker.project'),
        ),
    ]
