# Generated by Django 4.2.4 on 2023-09-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugTracker', '0013_remove_comments_created_at_alter_comments_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
