# Generated by Django 4.2.4 on 2023-09-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugTracker', '0015_bugs_resolved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugs',
            name='bug_fix',
        ),
    ]
