# Generated by Django 4.2.5 on 2023-09-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugTracker', '0016_remove_bugs_bug_fix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
