# Generated by Django 4.2.5 on 2023-10-12 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('high', 'High'), ('mid', 'Mid'), ('low', 'Low')], default='mid', max_length=10)),
                ('open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignees', models.ManyToManyField(related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='project.project')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_bugs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
